name: Upload www to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - .github/workflows/www-to-ft.yml


jobs:
  upload-package-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_DATETIME_V0_WWW }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - run: cd datetime.fifthtry.site && ls
      - name: Upload to FifthTry using fastn
        run: fastn upload datetime-v0 
  upload-example-to-fifthtry:
    needs: upload-package-to-fifthtry
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_DATETIME_EXAMPLE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - run: cd datetime-example.fifthtry.site && ls
      - name: Upload to FifthTry using fastn
        run: fastn upload datetime-example
